title: Yuan's Blog 
SEOTitle: yuanyuanyuan
description: A fish
show_downloads: true 
google_analytics:
theme: jekyll-theme-minimal
url: "https://y18810919727.github.io"
paginate: 5
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
plugins: 
    - jekyll-paginate
